repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-aws-credentials
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      - id: black
        language_version: python3.9
    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
      - id: flake8
    - repo: https://github.com/pycqa/bandit
      rev: 1.7.4
      hooks:
      - id: bandit
