repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-aws-credentials
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
      - id: black
        language_version: python3.10
    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
      - id: flake8
    - repo: https://github.com/pycqa/bandit
      rev: 1.7.8
      hooks:
      - id: bandit
